config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here

  namespace :admin do
    resources :third_party_services do
      member do
        patch :enable
        patch :disable
      end
    end

    resources :pages
  end
end

app/models/spree/page.rb
module Spree
  class Page < Spree::Base

    ## CONSTANTS
    NAME_REGEXP = /\A[a-zA-Z]+(\/[a-zA-Z]+)+/

    ## ASSOCIATIONS
    has_many :page_third_party_services
    has_many :third_party_services, through: :page_third_party_services, dependent: :destroy
    
    ## VALIDATIONS
    validates :name, presence: true, 
                     uniqueness: { case_sensitive: false }, 
                     format: { with: NAME_REGEXP,
                               allow_blank: true }

    ## CALLBACKS
    before_save :set_name_to_lowercase, if: :name_changed?

    self.whitelisted_ransackable_attributes = %w[name]


    def enabled_scripts
      third_party_services.enabled.pluck(:script)
    end

    private
      def set_name_to_lowercase
        name.downcase!
      end
  end
end

app/models/spree/page_third_party_service.rb
module Spree
  class PageThirdPartyService < Spree::Base

    ## ASSOCIATIONS
    belongs_to :page
    belongs_to :third_party_service

    ## VALIDATIONS
    validates :page_id, uniqueness: { scope: :third_party_service_id } 
  end
end

app/models/spree/third_party_service.rb
module Spree
  class ThirdPartyService < Spree::Base

    ## CONSTANTS
    SCRIPT_MAX_LENGTH = 65535

    ## ASSOCIATIONS
    has_many :page_third_party_services
    has_many :pages, through: :page_third_party_services, dependent: :destroy

    ## VALIDATIONS
    with_options presence: true do
      validates :name, uniqueness: { case_sensitive: false }
      validates :script, length: { maximum: SCRIPT_MAX_LENGTH }
    end

    ## SCOPES
    scope :enabled, -> { where(enabled: true) }

    self.whitelisted_ransackable_attributes = %w[name enabled]

    def enable
      update(enabled: true)
    end

    def disable
      update(enabled: false)
    end
  end
end

app/controllers/spree/admin/pages_controller.rb
module Spree
  module Admin
    class PagesController < ResourceController

      def index
        params[:q] ||= {}
        params[:q][:s] ||= 'name asc'
        @search = Spree::Page.ransack(params[:q])
        @pages = @search.result
      end

      def show
        redirect_to action: :edit
      end
    end
  end
end

app/controllers/spree/admin/third_party_services_controller.rb
module Spree
  module Admin
    class ThirdPartyServicesController < ResourceController

      before_action :load_pages, only: [:new, :edit, :create, :update]

      def index
        params[:q] ||= {}
        params[:q][:s] ||= 'name asc'
        @search = Spree::ThirdPartyService.ransack(params[:q])
        @third_party_services = @search.result
      end

      def show
        redirect_to action: :edit
      end

      def enable
        if @third_party_service.enable
          render json: { enabled: 'Yes' }, status: 200
        else
          render json: { error: @third_party_service.errors.full_messages.join(', ') }, status: 422
        end
      end

      def disable
        if @third_party_service.disable
          render json: { enabled: 'No' }, status: 200
        else
          render json: { error: @third_party_service.errors.full_messages.join(', ') }, status: 422
        end
      end

      private
        def load_pages
          @pages = Spree::Page.order(:name)
        end

        def third_party_service_params
          params.require(:third_party_service).permit(:name, :enabled, :script, page_ids: [])
        end
    end
  end
end

app/helpers/frontend_helper_decorator.rb
module Spree
  module FrontendHelper
    def current_page(controller, action)
      page_name = controller + '/' + action
      @current_page ||= Spree::Page.find_by_name(page_name)
    end
  end
end

app/helpers/spree/admin/third_party_services_helper.rb
module Spree
  module Admin
    module ThirdPartyServicesHelper
      def enabled(third_party_service)
        if third_party_service.enabled?
          'Yes'
        else
          'No'
        end
      end

      def url_to_toggle_enabled(third_party_service)
        if third_party_service.enabled?
          disable_admin_third_party_service_path(third_party_service)
        else
          enable_admin_third_party_service_path(third_party_service)
        end
      end

      def get_page_options(third_party_service, all_pages, selected_pages)
        first_option = pages_first_option(third_party_service, all_pages, selected_pages)
        all_pages.pluck(:name, :id).unshift(first_option)
      end

      def pages_first_option(third_party_service, all_pages, selected_pages)
        if(are_all_pages_selected?(all_pages, selected_pages))
          ['Remove All', 'select']
        else
          ['Select All', 'select']
        end
      end

      def are_all_pages_selected?(all_pages, selected_pages)
        all_pages.size == selected_pages.size
      end

      def get_selected_pages_ids(third_party_service)
        third_party_service.pages.map{ |page| page.id }
      end

    end
  end
end

app/helpers/spree/frontend_helper_decorator.rb
module Spree::FrontendHelper
  def current_page(controller, action)
    page_name = controller + '/' + action
    @current_page ||= Spree::Page.find_by_name(page_name)
  end
end

app/helpers/spree/third_party_helper.rb
module Spree::ThirdPartyHelper
  def current_page(controller, action)
    page_name = controller + '/' + action
    @current_page ||= Spree::Page.find_by_name(page_name)
  end

  module_function :current_page
end

app/helpers/spree/third_party_services_helper.rb
module Spree
  module ThirdPartyServicesHelper
    def current_page(controller, action)
      page_name = controller + '/' + action
      @current_page ||= Spree::Page.find_by_name(page_name)
    end
  end
end

app/views/spree/admin/pages/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @page } %>

<div data-hook="admin_page_form_fields">
  <div data-hook="admin_page_form_name">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
      <%= f.text_field :name, class: 'form-control title' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
</div>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:pages), spree.admin_pages_url %> /
  <%= @page.name %>
<% end %>

<%= form_for [:admin, @page], method: :put do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Page) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_page' } %>
<% end %>

<% if @pages.any? %>
  <table class="table" id="listing_pages">
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th><%= sort_link @search, :name, Spree.t(:name), { default: :desc }, {title: 'admin_pages_listing_name_title'} %></th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr id="<%= spree_dom_id page %>" data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="page"><%= page.name %></td>
          <td class="actions actions-2 text-right" data-hook="admin_pages_index_row_actions">
            <%= link_to_edit page, no_text: true, class: 'edit pull-right' %>
            <%= link_to_delete page, no_text: true, class: 'pull-right' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Page)) %>,
    <%= link_to Spree.t(:add_one), new_object_url  %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:pages), spree.admin_pages_url %> /
  <%= Spree.t(:new_page) %>
<% end %>

<%= form_for [:admin, @page] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/shared/sub_menu/_third_party_services.html.erb
<ul id="sidebar-third-party-services" class="collapse nav nav-pills nav-stacked" data-hook="admin_third_party_services_sub_tabs">
  <%= tab :third_party_services, label: Spree.t(:services) %>
  <%= tab :pages %>
</ul>

app/views/spree/admin/third_party_services/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @third_party_service } %>

<%= javascript_include_tag 'spree/backend/third_party_service_select2' %>
<%= javascript_include_tag 'spree/backend/select_all_option_manager' %>

<div data-hook="admin_third_party_service_form_fields">
  <div data-hook="admin_third_party_service_form_name">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
      <%= f.text_field :name, class: 'form-control title' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div data-hook="admin_third_party_service_form_enabled">
    <%= f.field_container :enabled, class: ['form-group'] do %>
      <%= f.label :enabled, Spree.t(:enabled) %>
      <%= f.error_message_on :enabled %>
      <%= f.check_box :enabled, class: 'form-control' %>
    <% end %>
  </div>

  <div data-hook="admin_third_party_service_form_script">
    <%= f.field_container :script, class: ['form-group'] do %>
      <%= f.label :script, raw(Spree.t(:script) + content_tag(:span, ' *', class: 'required')) %>
      <p class="help-block"><%= Spree.t(:script_field_note) %></p>
      <%= f.text_area :script, { rows: "16", class: 'form-control' } %>
      <%= f.error_message_on :script %>
    <% end %>
  </div>

  <div data-hook="admin_third_party_service_from_pages">
    <%= f.field_container :pages, class: ['form-group'] do %>
      <%= f.label :page_ids, Spree.t(:pages) %>
      <% unless @pages.present? %>
        <div class="alert alert-info">
          <%= Spree.t(:no_pages_exist) %>
          <%= link_to Spree.t(:here), new_admin_page_path  %>!
        </div>
      <% else %>
        <%= f.select :page_ids, options_for_select(get_page_options(@third_party_service, @pages, @third_party_service.pages), get_selected_pages_ids(@third_party_service)), {}, { multiple: true, class: 'select2', data: { select_all: are_all_pages_selected?(@pages, @third_party_service.pages) } } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spree/admin/third_party_services/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:third_party_services), spree.admin_third_party_services_url %> /
  <%= @third_party_service.name %>
<% end %>

<%= form_for [:admin, @third_party_service], method: :put do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/third_party_services/index.html.erb
<%= stylesheet_link_tag 'spree/backend/toggle_switch' %>
<%= javascript_include_tag 'spree/backend/third_party_service_toggler' %>

<% content_for :page_title do %>
  <%= plural_resource_name(Spree::ThirdPartyService) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_third_party_service), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_third_party_service' } %>
<% end %>

<% if @third_party_services.any? %>
  <table class="table" id="listing_third_party_services">
    <thead>
      <tr data-hook="admin_third_party_services_index_headers">
        <th><%= sort_link @search, :name, Spree.t(:name), { default: :desc }, {title: 'admin_third_party_services_listing_name_title'} %></th>
        <th><%= sort_link @search, :enabled, Spree.t(:enabled), { default: :desc }, {title: 'admin_third_party_services_listing_enabled_title'}  %></th>
        <th data-hook="admin_third_party_services_index_header_actions" class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% @third_party_services.each do |service| %>
        <tr id="<%= spree_dom_id service %>" data-hook="admin_third_party_services_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="name"><%= service.name %></td>
          <td class="enabled"><%= enabled(service) %></td>
          <td class="actions actions-3 text-right switch-td" data-hook="admin_third_party_services_index_row_actions">
            <label class="switch">
              <input type="checkbox" data-toggle-switch='yes' data-service-id='<%= service.id %>' <%= 'checked' if service.enabled %> data-enabled = <%= enabled(service) %> >
              <span class="slider round"></span>
            </label>
            <%= link_to_delete service, no_text: true, class: 'pull-right' %>
            <%= link_to_edit service, no_text: true, class: 'edit pull-right' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ThirdPartyService)) %>,
    <%= link_to Spree.t(:add_one), new_object_url  %>!
  </div>
<% end %>

app/views/spree/admin/third_party_services/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:third_party_services), spree.admin_third_party_services_url %> /
  <%= Spree.t(:new_third_party_service) %>
<% end %>

<%= form_for [:admin, @third_party_service] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/shared/_third_party_services_scripts.html.erb
<% if (@current_page = Spree::ThirdPartyHelper.current_page(params[:controller], params[:action])).present? %>
  <% @current_page.enabled_scripts.each do |script| %>
    <%= javascript_tag script %>
  <% end %>
<% end %>

app/views/spree/shared/third_party_services/_third_party_services_scripts.html.erb
<% if current_page(params[:controller], params[:action]).present? %>
  <% @current_page.enabled_scripts.each do |script| %>
    <%= javascript_tag script %>
  <% end %>
<% end %>